// Generated by CoffeeScript 1.9.0

/*
#
 * For: 读取mobile.json，生成获奖电话号码(html格式)
 * 使用：node getmobile.js
#
 */

(function() {
  var DB, fs, html, _;

  _ = require('underscore');

  fs = require('fs');

  DB = require('jsonfile');

  html = "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>获奖电话列表</title></head><body><table style='margin:30px;text-align:left;'><tr><th>电话号码</th></tr>";

  DB.readFile('./mobile.json', function(err, obj) {
    var mobileList, tmpMobileArray;
    if (err) {
      return console.log(err);
    } else {
      mobileList = obj;
      tmpMobileArray = _.keys(mobileList);
      _.each(tmpMobileArray, (function(_this) {
        return function(value, key) {
          if (value.charAt(0) === 'm') {
            return html += "<tr><td>" + value.slice(1) + "</td></tr>";
          }
        };
      })(this));
      html += "</table></body></html>";
      return fs.writeFile('./获奖电话号码.html', html, function(err) {
        if (err) {
          return console.log(err);
        }
      });
    }
  });

}).call(this);
